package com.auth.server.models;

// Generated 17 May, 2013 12:13:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * Channel generated by hbm2java
 */

public class Channel implements java.io.Serializable {





    public enum SyncStatus {
        ON,
        OFF,
        NOT_AVAILABLE
    }

    public enum SyncExecutionStatus {
        RUNNING,
        QUEUED,
        IDLE
    }

    public enum InvoiceAdjustmentType {
        NO_ADJUSTMENT,
        ADJUST_SELLING_PRICE_AND_DISCOUNT_BATCH_WISE,
        ADJUST_SELLING_PRICE_BATCH_WISE
    }


}
